version: "3.7"
services:
    
    nginx_app:
        build:
            context: ./build/nginx_app
            args:
                NGINX_AUTH_USER: testuser
                NGINX_AUTH_PASSWORD: testpw
        volumes:
            # NOTE must use literal "static" dir name here because otherwise requires URL strip/rewrite logic in conf
            - docker_staticfiles:/tmp/django_files/static
            - shared_sockets:/tmp/shared_sockets
            - quasar_dist:/tmp/quasar_dist
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
        command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/ng_dev.conf"]
    
    django_app:
        build: ./build/django_app
        volumes:
            - ./mount/django_app:/home/user/app_src
            - ./mount/database:/home/user/database
            - docker_staticfiles:/tmp/staticfiles
            - shared_sockets:/tmp/shared_sockets
    
    quasar_app:
        build: ./build/quasar_app
        volumes:
            - ./mount/quasar_app:/home/node/node_app/app_src
            - quasar_dist:/home/node/node_app/app_dist

volumes:
    shared_sockets: {}
    docker_staticfiles: {}
    quasar_dist: {}
