version: "3.7"
services:
    
    nginx_app:
        build:
            context: ./build/nginx_app
        volumes:
            # NOTE must use literal "static" dir name here because otherwise requires URL strip/rewrite logic in nginx conf
            - django_staticfiles:/tmp/django_files/static
            - quasar_dist:/tmp/quasar_dist
            - shared_sockets:/tmp/shared_sockets
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
        command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/ng_dev.conf"]
    
    django_app:
        build: ./build/django_app
        volumes:
            - ./mount/django_app:/home/user/app_src
            - ./mount/database:/home/user/database
            - django_staticfiles:/tmp/staticfiles
            - shared_sockets:/tmp/shared_sockets
        environment:
            - DJANGO_DEV_ENV=1
    
    quasar_app:
        build: ./build/quasar_app
        volumes:
            - ./mount/quasar_app:/home/node/node_app/app_src
            - quasar_dist:/home/node/node_app/app_dist
        ports:
            - 127.0.0.1:8080:8080

volumes:
    shared_sockets: {}
    django_staticfiles: {}
    quasar_dist: {}
