version: "3.7"
services:
    
    nginx_app:
        build:
            context: ./build/nginx_app
        volumes:
            # NOTE must use literal "static" dir name here because otherwise requires URL strip/rewrite logic in nginx conf
            - docker_staticfiles:/tmp/django_files/static:ro
            - shared_sockets:/tmp/shared_sockets
            - quasar_dist:/tmp/quasar_dist:ro
        ports:
            - 127.0.0.1:80:80
            - 127.0.0.1:443:443
        command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/ng_prod.conf"]
    
    django_app:
        build: ./build/django_app
        volumes:
            - ./mount/django_app:/home/user/app_src
            - ./mount/database:/home/user/database
            - docker_staticfiles:/tmp/staticfiles
            - shared_sockets:/tmp/shared_sockets
        environment:
            - DJANGO_DEV_ENV=0

volumes:
    shared_sockets: {}
    docker_staticfiles: {}
    quasar_dist: {}
